### ISSUE TITLE
Linking strategy between platform and key tokens

### ISSUE THREAD

**Issue by ionut-arm** [thomas-fossati/draft-kat#1]
We need to write up a detailed description of how the tokens in the KAT Bundle/EAT collection are (cryptographically) linked together. This might have to build upon the more generic description that will be added to the [EAT collection draft](https://thomas-fossati.github.io/draft-kat/draft-bft-rats-kat.html#I-D.frost-rats-eat-collection).

These details are also relevant to the security of the token and bundle, so should also be mentioned in the Security Considerations section.

**Comment by thomas-fossati** [comment]
I have a few notes to share:


# evidence composition

the goal is to model layered attestation environments and attestation of composite devices.

two models are discussed, direct and delegated, describing the split of responsibilities between pairs of cooperating attesters, A and B, which are typically arranged in a parent/child relationship reflecting their relative order in the system's chain of trust (CoT)

## direct

in the direct model, attester A entrusts attester B for collecting claims about B's target environment

B does not sign its claims, A does.

## delegated

in the delegated model, attester A entrusts attester B for collecting and signing claims about B's target environment

## cross-evidence binding

a "evidence binder" is a EAT claim that models CoT links between attesting environments.  it encodes the linkage between pairs of evidence produced by different attesters (A and B) in a EAT collection.

(assumption: trust delegation is tree-like)

the high level idea is to sample B's state at a certain point in time and inject an "image" thereof (the binder's value) into A, basically treating B as part of A's target environment

more precisely, the proposal is to:

* select a "representative" subset of B's claims
* wrap their values in a self-delimiting structure
* serialise the wrapping structure into a byte string
* cryptographically digest said byte string
* let A add the computed digest to its target environment

finally, let A and B independently compute evidence for their target environments.

### binding freshness

when either end of the binding operation (A or B) change their state, their binding becomes stale and must be recomputed

### binder description

it may be desirable for simplifying appraisal to explicitly encode the instructions for describing (and therefore verifying) the binding in a claim.
 
to that end, the binding function described in {{cross-evidence-binding}} needs to be specified unambiguously.
 
we make the following assumptions:

* the digest is a known hash function (e.g., one from the COSE algorithms)
* the input is a ordered subset of B's claims
* the output is a claim in the bound token
 
Then B could have a "binder description" claim as follows:

```cddl
; $hash-algo-id($binding-ctx, $claim-key_0, ..., $claim-key_n) => $bound-token-id[$out]
;
token-binder = [
    bind-f: hash-algo-id
    params: [ binding-ctx, + claim-key ]
    dst: [ bound-token-id, claim-key ]
]
 
binding-ctx = text
claim-key = int / text
hash-algo-id = int / text
bound-token-id = int / text
```
 
which may be instantiated as:
 
```
[
  -16, / SHA-256 /
  [
    "key-attestation-token",
    8 / TIK public in cnf /
  ],
  [
    "psa-token", / PSA platform token id in the EAT collection /
    10 / nonce /
  ]
]
```
